import Head from 'next/head'
import Content from "../../components/Content";

export default function Home() {
    return (
        <>
            <Head>
                <title>Lyane Lamara | Links</title>
                <meta name="Lyane Lamara | Links" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
            <Content/>
        </>
    )
}
