import Head from 'next/head'
import Content from '../../components/Content'
import {useEffect} from 'react'
import toast, {Toaster} from 'react-hot-toast'

export default function Home() {

    const WELCOME = () => toast.error('Welcome!', {
        position: 'top-right',
        duration: 2500,
        icon: '👋',
        id: 'ID'
    })

    useEffect(() => {
        WELCOME()
    }, []);

    return (
        <>
            <Head>
                <title>Lyane Lamara | Links</title>
                <meta name="Lyane Lamara | Links" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
            <Content/>
            <Toaster/>
        </>
    )
}
